/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'rank' : bigint,
  'score' : bigint,
  'playerName' : string,
}
export interface Question {
  'id' : bigint,
  'difficulty' : QuestionDifficulty,
  'explanation' : string,
  'category' : QuestionCategory,
  'statements' : Array<string>,
  'lieIndex' : bigint,
}
export type QuestionCategory = { 'logicalReasoning' : null } |
  { 'biology' : null } |
  { 'politicalScience' : null } |
  { 'history' : null } |
  { 'chemistry' : null } |
  { 'mathematics' : null } |
  { 'physics' : null } |
  { 'generalKnowledge' : null };
export type QuestionDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'moderate' : null };
export interface UserProfile {
  'emailOrPhone' : string,
  'name' : string,
  'badges' : Array<string>,
  'highestStreak' : bigint,
  'totalScore' : bigint,
  'currentLevel' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<
    [QuestionCategory, QuestionDifficulty, Array<string>, bigint, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[Principal, string], undefined>,
  'confirmPayment' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyChallenge' : ActorMethod<[], [] | [Question]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getQuestions' : ActorMethod<
    [QuestionCategory, QuestionDifficulty],
    Array<Question>
  >,
  'getTournamentLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTournamentQuestions' : ActorMethod<[], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordGameSession' : ActorMethod<
    [QuestionCategory, QuestionDifficulty, bigint, bigint],
    undefined
  >,
  'register' : ActorMethod<[string, string], undefined>,
  'registerTournament' : ActorMethod<[string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTournamentSession' : ActorMethod<
    [bigint, Array<bigint>, bigint],
    undefined
  >,
  'updateProfileName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];