/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionCategory = IDL.Variant({
  'logicalReasoning' : IDL.Null,
  'biology' : IDL.Null,
  'politicalScience' : IDL.Null,
  'history' : IDL.Null,
  'chemistry' : IDL.Null,
  'mathematics' : IDL.Null,
  'physics' : IDL.Null,
  'generalKnowledge' : IDL.Null,
});
export const QuestionDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'moderate' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'emailOrPhone' : IDL.Text,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'highestStreak' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'currentLevel' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : QuestionDifficulty,
  'explanation' : IDL.Text,
  'category' : QuestionCategory,
  'statements' : IDL.Vec(IDL.Text),
  'lieIndex' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [
        QuestionCategory,
        QuestionDifficulty,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyChallenge' : IDL.Func([], [IDL.Opt(Question)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getQuestions' : IDL.Func(
      [QuestionCategory, QuestionDifficulty],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getTournamentLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTournamentQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGameSession' : IDL.Func(
      [QuestionCategory, QuestionDifficulty, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerTournament' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTournamentSession' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
  'updateProfileName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionCategory = IDL.Variant({
    'logicalReasoning' : IDL.Null,
    'biology' : IDL.Null,
    'politicalScience' : IDL.Null,
    'history' : IDL.Null,
    'chemistry' : IDL.Null,
    'mathematics' : IDL.Null,
    'physics' : IDL.Null,
    'generalKnowledge' : IDL.Null,
  });
  const QuestionDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'emailOrPhone' : IDL.Text,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'highestStreak' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'currentLevel' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : QuestionDifficulty,
    'explanation' : IDL.Text,
    'category' : QuestionCategory,
    'statements' : IDL.Vec(IDL.Text),
    'lieIndex' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [
          QuestionCategory,
          QuestionDifficulty,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyChallenge' : IDL.Func([], [IDL.Opt(Question)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getQuestions' : IDL.Func(
        [QuestionCategory, QuestionDifficulty],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getTournamentLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTournamentQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGameSession' : IDL.Func(
        [QuestionCategory, QuestionDifficulty, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerTournament' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTournamentSession' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
    'updateProfileName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };