/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    rank: bigint;
    score: bigint;
    playerName: string;
}
export interface Question {
    id: bigint;
    difficulty: QuestionDifficulty;
    explanation: string;
    category: QuestionCategory;
    statements: Array<string>;
    lieIndex: bigint;
}
export interface UserProfile {
    emailOrPhone: string;
    name: string;
    badges: Array<string>;
    highestStreak: bigint;
    totalScore: bigint;
    currentLevel: bigint;
}
export enum QuestionCategory {
    logicalReasoning = "logicalReasoning",
    biology = "biology",
    politicalScience = "politicalScience",
    history = "history",
    chemistry = "chemistry",
    mathematics = "mathematics",
    physics = "physics",
    generalKnowledge = "generalKnowledge"
}
export enum QuestionDifficulty {
    easy = "easy",
    hard = "hard",
    moderate = "moderate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuestion(category: QuestionCategory, difficulty: QuestionDifficulty, statements: Array<string>, lieIndex: bigint, explanation: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBadge(user: Principal, badgeName: string): Promise<void>;
    confirmPayment(registrationId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyChallenge(): Promise<Question | null>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getProfile(): Promise<UserProfile>;
    getQuestions(category: QuestionCategory, difficulty: QuestionDifficulty): Promise<Array<Question>>;
    getTournamentLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getTournamentQuestions(): Promise<Array<Question>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordGameSession(category: QuestionCategory, difficulty: QuestionDifficulty, score: bigint, streak: bigint): Promise<void>;
    register(name: string, emailOrPhone: string): Promise<void>;
    registerTournament(name: string, mobileNumber: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitTournamentSession(registrationId: bigint, answers: Array<bigint>, score: bigint): Promise<void>;
    updateProfileName(newName: string): Promise<void>;
}
import type { Question as _Question, QuestionCategory as _QuestionCategory, QuestionDifficulty as _QuestionDifficulty, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: QuestionCategory, arg1: QuestionDifficulty, arg2: Array<string>, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBadge(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, arg1);
            return result;
        }
    }
    async confirmPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyChallenge(): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChallenge();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChallenge();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getQuestions(arg0: QuestionCategory, arg1: QuestionDifficulty): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentLeaderboard();
            return result;
        }
    }
    async getTournamentQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentQuestions();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentQuestions();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordGameSession(arg0: QuestionCategory, arg1: QuestionDifficulty, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameSession(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameSession(to_candid_QuestionCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_QuestionDifficulty_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return result;
        }
    }
    async registerTournament(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTournament(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitTournamentSession(arg0: bigint, arg1: Array<bigint>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTournamentSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTournamentSession(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProfileName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileName(arg0);
            return result;
        }
    }
}
function from_candid_QuestionCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionCategory): QuestionCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionDifficulty_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionDifficulty): QuestionDifficulty {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : from_candid_Question_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: _QuestionDifficulty;
    explanation: string;
    category: _QuestionCategory;
    statements: Array<string>;
    lieIndex: bigint;
}): {
    id: bigint;
    difficulty: QuestionDifficulty;
    explanation: string;
    category: QuestionCategory;
    statements: Array<string>;
    lieIndex: bigint;
} {
    return {
        id: value.id,
        difficulty: from_candid_QuestionDifficulty_n13(_uploadFile, _downloadFile, value.difficulty),
        explanation: value.explanation,
        category: from_candid_QuestionCategory_n15(_uploadFile, _downloadFile, value.category),
        statements: value.statements,
        lieIndex: value.lieIndex
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    moderate: null;
}): QuestionDifficulty {
    return "easy" in value ? QuestionDifficulty.easy : "hard" in value ? QuestionDifficulty.hard : "moderate" in value ? QuestionDifficulty.moderate : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logicalReasoning: null;
} | {
    biology: null;
} | {
    politicalScience: null;
} | {
    history: null;
} | {
    chemistry: null;
} | {
    mathematics: null;
} | {
    physics: null;
} | {
    generalKnowledge: null;
}): QuestionCategory {
    return "logicalReasoning" in value ? QuestionCategory.logicalReasoning : "biology" in value ? QuestionCategory.biology : "politicalScience" in value ? QuestionCategory.politicalScience : "history" in value ? QuestionCategory.history : "chemistry" in value ? QuestionCategory.chemistry : "mathematics" in value ? QuestionCategory.mathematics : "physics" in value ? QuestionCategory.physics : "generalKnowledge" in value ? QuestionCategory.generalKnowledge : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n11(_uploadFile, _downloadFile, x));
}
function to_candid_QuestionCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): _QuestionCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionDifficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionDifficulty): _QuestionDifficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCategory): {
    logicalReasoning: null;
} | {
    biology: null;
} | {
    politicalScience: null;
} | {
    history: null;
} | {
    chemistry: null;
} | {
    mathematics: null;
} | {
    physics: null;
} | {
    generalKnowledge: null;
} {
    return value == QuestionCategory.logicalReasoning ? {
        logicalReasoning: null
    } : value == QuestionCategory.biology ? {
        biology: null
    } : value == QuestionCategory.politicalScience ? {
        politicalScience: null
    } : value == QuestionCategory.history ? {
        history: null
    } : value == QuestionCategory.chemistry ? {
        chemistry: null
    } : value == QuestionCategory.mathematics ? {
        mathematics: null
    } : value == QuestionCategory.physics ? {
        physics: null
    } : value == QuestionCategory.generalKnowledge ? {
        generalKnowledge: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionDifficulty): {
    easy: null;
} | {
    hard: null;
} | {
    moderate: null;
} {
    return value == QuestionDifficulty.easy ? {
        easy: null
    } : value == QuestionDifficulty.hard ? {
        hard: null
    } : value == QuestionDifficulty.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
